id: IFACEF2B1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T16:43:02+00:00'
last_modified: '2022-06-08T12:26:41.462399+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25219
  title: སངས་རྒྱས་ཀྱི་བསྟན་པ་རིན་པོ་ཆེའི་སྙིང་པོའི་བསྡུས་དོན་ཕན་བདེའི་འོད་སྣང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A8D6:
      image_group_id: I4896
      title: ''
      total_pages: 194
      order: 1
      base_file: A8D6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
