id: P009636
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W25219
  title: སངས་རྒྱས་ཀྱི་བསྟན་པ་རིན་པོ་ཆེའི་སྙིང་པོའི་བསྡུས་དོན་ཕན་བདེའི་འོད་སྣང
  author: ''
  volumes:
    40b7da8df8184ff691a1c83a92363c52:
      image_group_id: I4896
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
